"""Amazon S3 Vectors backend for RAG retrieval.

State of the art on AWS for cost-effective RAG: S3 Vectors is a purpose-built S3
bucket type that stores and queries embeddings through a dedicated API
(``boto3.client("s3vectors")``) with no infrastructure to provision — you pay for
storage + queries instead of a standing OpenSearch/Aurora cluster. Optimized for
infrequent queries (sub-second latency), which fits a document-grounded RAG service.

This managed-via-SDK path (not the console/Knowledge Bases path) keeps the same
`VectorStore` contract the rest of the app expects:

- ``add_documents(texts, metadata)`` — embeds with the configured provider and
  ``put_vectors`` into the index. Document text is stored as non-filterable metadata.
- ``search(query)`` — embeds the query and ``query_vectors`` for top-k nearest.

Embeddings are generated by the injected `LLMProvider` (Amazon Titan Text Embeddings
V2 in the full-AWS setup), so this store stays embedding-model agnostic.

The ``boto3`` import and client are created lazily so local dev and CI (which never
talk to AWS) don't need credentials; tests inject a fake client.
"""

from __future__ import annotations

import uuid
from typing import Any

from app.logging_config import structured_log
from app.providers.base import LLMProvider
from app.rag.retriever import RetrievedDoc

# S3 Vectors accepts up to 500 vectors per PutVectors call.
_PUT_BATCH = 500
# Key under which we stash the chunk text (declared non-filterable at index create).
_TEXT_KEY = "text"


class S3VectorStore:
    """Vector store backed by Amazon S3 Vectors (via the ``s3vectors`` API)."""

    def __init__(
        self,
        provider: LLMProvider,
        *,
        bucket: str,
        index: str,
        top_k: int = 4,
        region: str | None = None,
        dimension: int = 1024,
        distance_metric: str = "cosine",
        client: Any = None,
    ) -> None:
        if not bucket or not index:
            raise ValueError("S3VectorStore requires both 'bucket' and 'index'")
        self.provider = provider
        self.bucket = bucket
        self.index = index
        self.top_k = top_k
        self.region = region
        self.dimension = dimension
        self.distance_metric = distance_metric
        self._client = client
        self._count = 0

    @property
    def client(self) -> Any:
        if self._client is None:
            try:
                import boto3  # deferred: not needed for local/CI
            except ImportError as exc:  # pragma: no cover - only when boto3 absent
                raise RuntimeError(
                    "S3VectorStore requires boto3. Install it with: pip install boto3"
                ) from exc
            self._client = (
                boto3.client("s3vectors", region_name=self.region)
                if self.region
                else boto3.client("s3vectors")
            )
        return self._client

    def ensure_index(self) -> None:
        """Create the vector bucket + index if they do not exist (idempotent)."""
        try:
            self.client.create_vector_bucket(vectorBucketName=self.bucket)
        except Exception as exc:  # bucket already exists / conflict is fine
            structured_log("INFO", "s3vectors.bucket.exists", detail=str(exc))
        try:
            self.client.create_index(
                vectorBucketName=self.bucket,
                indexName=self.index,
                dataType="float32",
                dimension=self.dimension,
                distanceMetric=self.distance_metric,
                metadataConfiguration={"nonFilterableMetadataKeys": [_TEXT_KEY]},
            )
        except Exception as exc:  # index already exists / conflict is fine
            structured_log("INFO", "s3vectors.index.exists", detail=str(exc))

    async def add_documents(self, texts: list[str], metadata: list[dict] | None = None) -> None:
        if not texts:
            return
        vectors = await self.provider.embed(texts)
        items = []
        for i, (text, vector) in enumerate(zip(texts, vectors, strict=False)):
            meta = dict((metadata or [{}] * len(texts))[i]) if metadata else {}
            meta[_TEXT_KEY] = text
            items.append(
                {"key": uuid.uuid4().hex, "data": {"float32": list(vector)}, "metadata": meta}
            )

        for start in range(0, len(items), _PUT_BATCH):
            batch = items[start : start + _PUT_BATCH]
            self.client.put_vectors(
                vectorBucketName=self.bucket, indexName=self.index, vectors=batch
            )
        self._count += len(items)
        structured_log("INFO", "rag.add_documents", backend="s3_vectors", count=len(items))

    async def search(self, query: str) -> list[RetrievedDoc]:
        query_vector = (await self.provider.embed([query]))[0]
        resp = self.client.query_vectors(
            vectorBucketName=self.bucket,
            indexName=self.index,
            queryVector={"float32": list(query_vector)},
            topK=self.top_k,
            returnMetadata=True,
            returnDistance=True,
        )
        results: list[RetrievedDoc] = []
        for hit in resp.get("vectors", []):
            meta = hit.get("metadata", {}) or {}
            text = meta.get(_TEXT_KEY, "")
            results.append(
                RetrievedDoc(
                    chunk_id=hit.get("key", ""),
                    text=text,
                    score=self._to_score(hit.get("distance")),
                    metadata={k: v for k, v in meta.items() if k != _TEXT_KEY},
                )
            )
        structured_log(
            "INFO", "rag.search", backend="s3_vectors", query_len=len(query), hits=len(results)
        )
        return results

    def _to_score(self, distance: Any) -> float:
        """Convert an S3 Vectors distance into a higher-is-better similarity score."""
        if distance is None:
            return 0.0
        if self.distance_metric == "cosine":
            # cosine distance in [0, 2] -> similarity in [-1, 1]
            return round(1.0 - float(distance), 6)
        return round(-float(distance), 6)

    @property
    def size(self) -> int:
        """Live count of vectors in the index, best-effort.

        Queries S3 Vectors via paginated ``list_vectors`` so the number reflects
        what is actually stored (including vectors written by other processes),
        not just what this instance added. Falls back to the local add counter
        when the backend can't be listed (client without ``list_vectors``, or a
        transient error) so the value is never misleadingly zero.
        """
        live = self._live_count()
        return live if live is not None else self._count

    def _live_count(self) -> int | None:
        """Count vectors in the index via paginated ``list_vectors``, or ``None``."""
        lister = getattr(self.client, "list_vectors", None)
        if not callable(lister):
            return None
        try:
            total = 0
            token: str | None = None
            while True:
                kwargs: dict[str, Any] = {
                    "vectorBucketName": self.bucket,
                    "indexName": self.index,
                    "returnData": False,
                    "returnMetadata": False,
                }
                if token:
                    kwargs["nextToken"] = token
                resp = lister(**kwargs)
                total += len(resp.get("vectors", []))
                token = resp.get("nextToken")
                if not token:
                    break
            return total
        except Exception as exc:  # backend hiccup -> fall back to local counter
            structured_log("INFO", "s3vectors.count.fallback", detail=str(exc))
            return None
